insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (1, '1803-01-25', 'Mårten', 'McIntee');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (2, '1856-02-29', 'Edmée', 'Castiglioni');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (3, '1760-09-04', 'Eloïse', 'Bulley');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (4, '1915-03-28', 'Marylène', 'Ballister');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (5, '1967-05-18', 'Intéressant', 'Crevagh');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (6, '1924-06-30', 'Annotée', 'Ghioni');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (7, '1799-10-16', 'Lèi', 'Bilbey');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (8, '1728-01-16', 'Andréa', 'Morton');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (9, '1692-08-13', 'Torbjörn', 'Meynell');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (10, '1961-11-27', 'Maëlle', 'Chessor');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (11, '1638-10-23', 'Mylène', 'Wapple');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (12, '1652-05-14', 'Lorène', 'Sturman');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (13, '1631-12-02', 'Eléonore', 'De la Yglesia');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (14, '1878-03-30', 'Crééz', 'Stoltz');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (15, '1768-11-14', 'Clélia', 'Snaddon');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (16, '2019-12-13', 'Kévina', 'Wilder');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (17, '1732-04-20', 'Magdalène', 'Gallichiccio');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (18, '1633-03-11', 'Léone', 'Udell');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (19, '1945-09-29', 'Yú', 'Milbank');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (20, '1870-02-11', 'Clémentine', 'Blees');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (21, '1989-02-21', 'Ruì', 'Beare');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (22, '1665-10-21', 'Anaé', 'Joyson');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (23, '1986-03-12', 'Eloïse', 'Rivalant');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (24, '1800-10-11', 'Estée', 'Entwhistle');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (25, '1764-06-10', 'Réjane', 'Dell Casa');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (26, '1646-04-24', 'Vénus', 'Mariette');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (27, '1901-07-09', 'Naéva', 'Glanton');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (28, '1850-02-02', 'Salomé', 'Dumbelton');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (29, '1695-03-19', 'Médiamass', 'Guite');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (30, '1784-10-24', 'Léone', 'Kleinberer');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (31, '1653-11-07', 'Mylène', 'Yablsley');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (32, '1798-06-27', 'Fèi', 'Cocklie');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (33, '1763-10-30', 'Bérangère', 'Padmore');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (34, '1706-12-14', 'Marie-ève', 'Anchor');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (35, '1778-01-08', 'Océanne', 'Giacoppo');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (36, '1909-01-07', 'Maëly', 'Remmer');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (37, '1857-04-01', 'Stéphanie', 'Mayoh');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (38, '1725-01-04', 'Cloé', 'Gyves');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (39, '1674-07-30', 'Håkan', 'Aimson');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (40, '1702-08-20', 'Célia', 'Ilymanov');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (41, '1605-03-01', 'Anaïs', 'Hutcheon');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (42, '1683-02-12', 'Océane', 'Coade');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (43, '1857-05-04', 'Pénélope', 'Adelman');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (44, '1794-01-11', 'Célestine', 'Neubigging');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (45, '1624-12-29', 'Léa', 'Phayre');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (46, '1820-02-15', 'Josée', 'Leggs');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (47, '1729-03-24', 'Léane', 'Killough');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (48, '1995-03-07', 'Mélodie', 'Larimer');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (49, '1633-11-14', 'Lèi', 'Ebbing');
insert into COMPOSER (ID, DOB, FIRST_NAME, LAST_NAME) values (50, '1693-05-26', 'Eléonore', 'Tippings');

insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (1, 'Fortress 2', 1896, 'Movement', 24);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (2, 'Born Reckless', 1761, 'Chamber Music', 4);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (3, 'Never Again', 1842, 'Overture', 20);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (4, 'Bloodlust: Subspecies III', 1854, 'Movement', 3);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (5, 'Cornelis', 1636, 'Opera', 17);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (6, 'Leaving Las Vegas', 1768, 'Chamber Music', 32);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (7, 'Vampire Hunter D: Bloodlust (Banpaia hantâ D)', 1887, 'Aria', 29);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (8, 'Stateside', 1966, 'Aria', 44);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (9, 'Filming ''Othello''', 1669, 'Sonata', 22);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (10, 'Manufacturing Consent: Noam Chomsky and the Media', 1984, 'Symphony', 38);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (11, 'X-Men', 1829, 'Sonata', 27);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (12, 'Halloween H20: 20 Years Later (Halloween 7: The Revenge of Laurie Strode)', 1660, 'Opera', 36);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (13, 'High Heels and Low Lifes', 1638, 'Movement', 46);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (14, 'Retribution (Sakebi)', 1987, 'Cadenza', 45);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (15, 'In the Company of Men', 1792, 'Cadenza', 43);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (16, 'R100', 1607, 'Opera', 41);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (17, 'Ludwig', 1840, 'Symphony', 43);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (18, 'Gunbuster (Top wo Narae)', 1701, 'Overture', 16);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (19, 'Ike: Countdown to D-Day', 1634, 'Overture', 6);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (20, 'American Addict', 1748, 'Opus', 31);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (21, 'Hercules and the Amazon Women', 1861, 'Overture', 15);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (22, 'Day of the Triffids, The', 1714, 'Aria', 31);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (23, 'Last House on the Left, The', 1648, 'Symphony', 25);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (24, 'Dear John', 2013, 'Sonata', 24);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (25, 'Annie Get Your Gun', 1727, 'Chamber Music', 49);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (26, 'Mahoney''s Last Stand', 1918, 'Cadenza', 8);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (27, 'My Last Five Girlfriends', 1681, 'Concerto', 33);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (28, 'Private Lives of Pippa Lee, The', 1897, 'Opus', 48);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (29, 'Jaws 3-D', 1695, 'Aria', 10);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (30, 'A Cry in the Wild', 1882, 'Opera', 3);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (31, 'Only When I Laugh', 1696, 'Cadenza', 7);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (32, 'Parker', 1969, 'Symphony', 44);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (33, 'Shadow of the Thin Man', 1978, 'Cadenza', 26);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (34, 'Force of Evil', 1755, 'Opus', 15);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (35, 'Dinner with Friends', 1948, 'Symphony', 6);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (36, 'Out Cold', 1987, 'Opus', 19);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (37, 'Robin Hood', 1944, 'Aria', 18);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (38, 'Invaders from Mars', 1777, 'Symphony', 34);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (39, 'Answers to Nothing', 1832, 'Sonata', 1);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (40, 'Beautiful Joe', 1962, 'Chamber Music', 1);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (41, 'Time Masters (Maîtres du temps, Les)', 1993, 'Concerto', 8);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (42, 'Dark Journey', 1802, 'Chamber Music', 18);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (43, 'Fay Grim', 1740, 'Chamber Music', 33);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (44, 'Gravedancers, The', 2019, 'Cadenza', 26);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (45, 'Fierce Light: When Spirit Meets Action', 1723, 'Overture', 28);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (46, 'Blue Velvet', 1810, 'Chamber Music', 13);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (47, 'Package, The', 1942, 'Overture', 44);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (48, 'Royal Scandal, A', 1729, 'Overture', 29);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (49, 'Tall Guy, The', 1806, 'Cadenza', 42);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (50, 'Bon Cop, Bad Cop', 1755, 'Movement', 12);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (51, 'Triangle', 1931, 'Movement', 31);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (52, 'First Beautiful Thing, The (La prima cosa bella)', 1840, 'Symphony', 5);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (53, 'Alex and Emma', 1938, 'Overture', 13);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (54, 'Music Never Stopped, The', 1918, 'Opera', 36);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (55, 'Windy Day (Tuulinen päivä)', 1944, 'Opus', 47);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (56, 'Gambit', 2007, 'Symphony', 1);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (57, 'The Secret of Dr. Kildare', 1652, 'Sonata', 44);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (58, 'One, Two, Three', 1825, 'Sonata', 41);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (59, 'Valley of Head Hunters', 1898, 'Overture', 8);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (60, 'Rendition', 1643, 'Sonata', 41);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (61, 'Dangerous Davies: The Last Detective', 1825, 'Movement', 7);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (62, 'English Teacher, The', 1857, 'Cadenza', 36);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (63, 'Sound of Redemption: The Frank Morgan Story', 1624, 'Symphony', 33);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (64, 'Ripe', 1748, 'Concerto', 23);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (65, 'Friends with Benefits', 1854, 'Cadenza', 35);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (66, 'Vengeance: The Story of Tony Cimo', 1632, 'Opus', 36);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (67, 'Good Heart, The', 1635, 'Concerto', 22);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (68, 'Last Remake of Beau Geste, The', 1757, 'Opera', 44);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (69, 'Azumi', 1896, 'Cadenza', 36);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (70, 'Frida', 1812, 'Concerto', 37);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (71, 'Blood Creek (a.k.a. Town Creek)', 1912, 'Sonata', 13);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (72, 'Across the Line: The Exodus of Charlie Wright', 1817, 'Overture', 29);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (73, 'Dirty Shame, A', 1792, 'Movement', 23);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (74, 'Bloody Pit of Horror (Il boia scarlatto) (Virgins for the Hangman)', 1600, 'Movement', 27);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (75, 'North & South', 1886, 'Concerto', 21);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (76, 'The Skinny', 1930, 'Cadenza', 45);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (77, 'Little Girl Who Lives Down the Lane, The', 1670, 'Movement', 32);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (78, 'Facts of Life, The', 1793, 'Chamber Music', 41);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (79, 'Finding Normal', 1761, 'Aria', 35);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (80, 'The Grump', 1921, 'Movement', 12);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (81, 'Colder Kind of Death, A', 1603, 'Concerto', 33);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (82, 'Farewell, Home Sweet Home (Adieu, plancher des vaches!)', 1970, 'Opera', 36);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (83, 'Sicily! (Sicilia!)', 1827, 'Symphony', 39);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (84, 'Lady Windermere''s Fan', 1815, 'Movement', 2);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (85, 'Firaaq', 1854, 'Opera', 10);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (86, 'Divorcee, The', 1991, 'Cadenza', 12);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (87, 'Night of the Iguana, The', 1800, 'Opus', 44);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (88, 'Crocodile', 1965, 'Cadenza', 25);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (89, 'King Lear', 1942, 'Concerto', 18);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (90, 'Mermaids', 1707, 'Symphony', 37);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (91, 'Mysterians, The (Chikyu Boeigun)', 1987, 'Chamber Music', 31);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (92, 'Nine Lives of Fritz the Cat, The', 1661, 'Cadenza', 40);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (93, 'Fire Down Below', 1792, 'Chamber Music', 46);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (94, 'Wheel, The (La Roue)', 1676, 'Aria', 40);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (95, 'Enemy Mine', 1988, 'Aria', 35);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (96, 'Return to Horror High', 1987, 'Chamber Music', 26);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (97, 'Euphoria (Eyforiya)', 1994, 'Movement', 4);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (98, 'War of the Shaolin Temple (Shao Lin shi san gun seng)', 1867, 'Opera', 49);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (99, 'Forever, Darling', 1721, 'Opus', 41);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (100, 'Adventures of Tarzan', 1987, 'Aria', 47);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (101, 'Prison (Fängelse) ', 1950, 'Movement', 31);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (102, 'Mr. Moto''s Last Warning', 1905, 'Symphony', 6);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (103, 'Snakes on a Plane', 1745, 'Sonata', 5);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (104, 'Black Tights (1-2-3-4 ou Les Collants noirs)', 1677, 'Aria', 36);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (105, 'Sinbad: The Fifth Voyage', 1649, 'Concerto', 15);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (106, 'Pirates of Silicon Valley', 2010, 'Movement', 50);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (107, 'My New Gun', 1751, 'Sonata', 43);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (108, 'Revenge of the Pink Panther', 1761, 'Concerto', 24);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (109, 'I Dreamed of Africa', 1678, 'Sonata', 21);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (110, 'Hercules in New York', 1620, 'Cadenza', 35);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (111, 'Little Secrets', 1770, 'Symphony', 20);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (112, 'Nightmare on Elm Street 4: The Dream Master, A', 1670, 'Opus', 22);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (113, 'Charm School (Niñas mal)', 1614, 'Chamber Music', 44);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (114, 'Sharktopus', 1890, 'Cadenza', 33);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (115, 'Torrente 3: El protector', 1800, 'Concerto', 7);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (116, 'Pelle the Conqueror (Pelle erobreren)', 1927, 'Chamber Music', 2);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (117, 'Staying Alive', 1676, 'Chamber Music', 12);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (118, 'Pressed', 1663, 'Aria', 19);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (119, 'My Ain Folk', 1765, 'Sonata', 50);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (120, 'War Wagon, The', 1916, 'Aria', 45);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (121, 'On Deadly Ground', 1966, 'Cadenza', 8);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (122, 'Pocket Money', 1679, 'Aria', 1);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (123, 'Middle Men', 1798, 'Movement', 19);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (124, 'Grass Harp, The', 1991, 'Overture', 7);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (125, 'Too Many Husbands', 1681, 'Opera', 14);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (126, 'Meshes of the Afternoon', 1751, 'Chamber Music', 3);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (127, 'Girl Walks Into a Bar', 1627, 'Movement', 2);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (128, 'Funky Forest: The First Contact', 1928, 'Movement', 37);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (129, 'Heaven''s Gate', 1720, 'Opera', 3);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (130, '3-Iron (Bin-jip)', 1826, 'Chamber Music', 45);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (131, 'Kummeli Stories', 1651, 'Opera', 11);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (132, 'Boiling Point (3-4 x jûgatsu)', 2017, 'Overture', 5);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (133, 'Color of Friendship, The', 1916, 'Overture', 20);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (134, 'Tin Star, The', 1851, 'Aria', 8);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (135, 'Drawing Restraint 9', 1917, 'Cadenza', 11);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (136, 'Phantom of the Rue Morgue', 1606, 'Aria', 16);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (137, 'Black Windmill, The', 1920, 'Opus', 27);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (138, 'Hail the Conquering Hero', 1872, 'Overture', 50);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (139, 'Wind Journeys, The (Viajes del viento, Los)', 1878, 'Symphony', 21);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (140, 'Private Eyes, The', 1828, 'Cadenza', 41);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (141, 'Two Years at Sea', 1842, 'Opus', 50);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (142, 'Strike! (a.k.a. All I Wanna Do, The Hairy Bird)', 1849, 'Concerto', 22);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (143, 'My Left Foot', 1923, 'Overture', 17);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (144, 'Digging Up the Marrow', 1712, 'Movement', 23);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (145, 'Bebe''s Kids', 1920, 'Overture', 16);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (146, 'I Am', 1618, 'Chamber Music', 29);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (147, 'Frankenfish', 1808, 'Aria', 20);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (148, 'Bless the Child', 1929, 'Movement', 27);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (149, 'Mr. Warmth: The Don Rickles Project', 1699, 'Concerto', 11);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (150, 'Hits', 1869, 'Opus', 33);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (151, 'Life and Debt', 1733, 'Cadenza', 8);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (152, 'Happiest Millionaire, The', 1767, 'Aria', 33);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (153, 'Gunnin'' for That #1 Spot', 1773, 'Aria', 19);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (154, 'Big Trouble', 1827, 'Cadenza', 29);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (155, 'Houdini', 1664, 'Opera', 29);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (156, 'Lacemaker, The (Dentellière, La)', 1735, 'Chamber Music', 14);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (157, 'Showgirls', 1973, 'Cadenza', 6);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (158, 'Stakeout', 1753, 'Symphony', 29);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (159, 'Ah of Life, The', 1849, 'Sonata', 6);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (160, 'Nico and Dani (Krámpack)', 2015, 'Opera', 22);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (161, 'Plot Against Harry, The', 1709, 'Opera', 43);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (162, 'Conjuring, The', 1651, 'Opera', 12);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (163, 'Alien Nation: Body and Soul', 2016, 'Chamber Music', 48);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (164, 'Last Train Home', 1727, 'Aria', 47);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (165, 'Fateless (Sorstalanság)', 1989, 'Concerto', 21);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (166, 'Missing', 1827, 'Opera', 16);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (167, 'Turtle''s Tale 2: Sammy''s Escape from Paradise, A (Sammy''s avonturen 2) (Sammy''s Adventures 2)', 1939, 'Cadenza', 24);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (168, 'Venus & Fleur', 1828, 'Symphony', 26);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (169, 'Man, The', 1677, 'Sonata', 35);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (170, 'Desert Hearts', 1947, 'Cadenza', 25);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (171, 'No Time for Nuts', 1762, 'Aria', 10);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (172, 'Kevin Smith: Too Fat For 40', 1918, 'Cadenza', 24);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (173, 'Betty Blue (37°2 le matin)', 1674, 'Symphony', 9);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (174, 'Good Heart, The', 1606, 'Movement', 34);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (175, 'Red Like the Sky (Rosso come il cielo)', 1701, 'Opera', 20);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (176, 'Cruise, The', 1639, 'Sonata', 42);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (177, 'Voyage to the Beginning of the World (Viagem ao Princípio do Mundo)', 1622, 'Opus', 26);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (178, 'Something''s Gonna Live', 1929, 'Concerto', 28);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (179, 'Magnum Cop', 1632, 'Opus', 46);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (180, 'Have Rocket, Will Travel', 1814, 'Cadenza', 39);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (181, 'Leonard Cohen: I''m Your Man', 1924, 'Opus', 37);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (182, 'Lawless Street, A (Marshal of Medicine Bend)', 1779, 'Chamber Music', 28);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (183, 'Forgotten Silver', 1666, 'Aria', 31);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (184, 'Cheaper by the Dozen', 1868, 'Chamber Music', 3);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (185, 'Willow Creek', 1725, 'Opera', 3);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (186, 'Waydowntown', 1942, 'Overture', 6);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (187, 'The Story of Robin Hood and His Merrie Men', 1604, 'Opus', 48);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (188, 'Kiss or Kill', 1880, 'Cadenza', 35);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (189, 'Sidewalks of London (St. Martin''s Lane)', 2002, 'Opera', 8);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (190, 'Child Bride', 1687, 'Cadenza', 33);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (191, 'Over the Edge', 1622, 'Chamber Music', 17);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (192, 'Larry the Cable Guy: Health Inspector', 1630, 'Concerto', 13);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (193, '25 Watts', 1935, 'Opus', 25);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (194, 'Waist Deep', 1970, 'Sonata', 25);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (195, 'Longshots, The', 1721, 'Opus', 33);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (196, 'Thumbsucker', 1628, 'Opus', 42);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (197, '13', 1770, 'Opus', 22);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (198, 'Hitch', 1665, 'Opus', 13);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (199, 'Big Girls Don''t Cry (Große Mädchen weinen nicht)', 1994, 'Cadenza', 23);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (200, 'Slumming', 1653, 'Aria', 20);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (201, 'In the Time of the Butterflies', 1717, 'Overture', 48);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (202, 'Tooth Fairy', 1720, 'Chamber Music', 24);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (203, 'Rampart', 1909, 'Sonata', 23);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (204, 'Genghis Blues', 1678, 'Chamber Music', 2);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (205, 'Colour of Magic, The (Terry Pratchett''s The Colour of Magic)', 1743, 'Cadenza', 50);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (206, 'The Last Journey', 1970, 'Cadenza', 49);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (207, 'Cheech & Chong''s The Corsican Brothers', 1992, 'Cadenza', 21);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (208, 'House of Exorcism, The (a.k.a. Lisa and the Devil) (Casa dell''esorcismo, La)', 1848, 'Symphony', 28);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (209, 'Vice', 1605, 'Aria', 11);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (210, 'Upstream Color', 1913, 'Aria', 40);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (211, 'Family Guy Presents: It''s a Trap', 1890, 'Sonata', 47);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (212, 'Heaven Can Wait', 1749, 'Cadenza', 10);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (213, 'Mardock Scramble: The Second Combustion', 1849, 'Cadenza', 28);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (214, 'Patriotism (Yûkoku)', 1805, 'Aria', 23);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (215, 'Aviator, The', 1869, 'Opera', 9);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (216, 'Captive Heart: The James Mink Story', 1624, 'Opus', 2);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (217, 'The Love Letter', 1817, 'Opus', 46);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (218, 'Scent of Green Papaya, The (Mùi du du xhan - L''odeur de la papaye verte)', 1711, 'Overture', 17);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (219, 'My Best Enemy (Mi mejor enemigo)', 1943, 'Chamber Music', 21);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (220, 'Mom and Dad Save the World', 1838, 'Movement', 28);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (221, 'Cold Light of Day, The', 1711, 'Aria', 16);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (222, 'Who Is Harry Kellerman and Why Is He Saying Those Terrible Things About Me?', 1916, 'Symphony', 37);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (223, 'Moonstruck', 1668, 'Chamber Music', 50);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (224, 'Scorched', 1785, 'Movement', 39);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (225, 'Under Suspicion', 1877, 'Symphony', 21);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (226, 'By the Light of the Silvery Moon', 1650, 'Sonata', 20);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (227, 'Billy Bathgate', 1840, 'Opera', 44);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (228, 'Ballerina (La mort du cygne)', 1739, 'Concerto', 38);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (229, 'Hadersfild (Huddersfield)', 1907, 'Overture', 35);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (230, 'Creature', 1785, 'Opus', 48);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (231, 'Jerichow', 1806, 'Movement', 20);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (232, 'Rånarna', 1750, 'Symphony', 18);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (233, 'Sweet Movie', 1875, 'Opus', 13);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (234, 'Bookies', 1858, 'Concerto', 41);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (235, 'From Time to Time', 1729, 'Aria', 14);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (236, 'Feast at Midnight, A', 1663, 'Concerto', 46);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (237, 'The Big Shave', 1735, 'Opus', 41);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (238, 'Half Moon (a.k.a. Niwemang)', 1740, 'Chamber Music', 38);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (239, 'I Love Trouble', 1753, 'Opus', 24);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (240, 'Allegheny Uprising', 1663, 'Aria', 45);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (241, 'Big Parade, The', 1815, 'Opus', 26);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (242, 'Simple Wish, A', 2003, 'Movement', 1);
insert into MUSIC (ID, TITLE, YEAR_OF_COMPOSITION, STYLE, COMPOSER_ID) values (243, 'Mary of Scotland', 1892, 'Sonata', 30);
